services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev_network

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    env_file:
      - .env
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    expose:
      - "9200"
      - "9600"
    networks:
      - dev_network

  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    env_file:
      - .env
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    expose:
      - "9200"
      - "9600"
    networks:
      - dev_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - dev_network
  cognito:
    image: jagregory/cognito-local:latest
    ports:
      - "9229:9229"
    volumes:
      - ./cognito:/app/.cognito

  api:
    build:
      dockerfile: ../api.Dockerfile
      context: ./api
    ports:
      - "3000:3000"
    networks:
      - dev_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  opensearch-data1:
  opensearch-data2:

networks:
  dev_network:
    name: dev_network
    driver: bridge
